export const menu = [
  {
    id: 1,
    title: "Ada Çayı Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/ada1.png", "./imgs/SirkeImgs/ada2.png"],
  },
  {
    id: 2,
    title: "Alıç Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 60.00", "₺ 35.00"],
    img: ["./imgs/SirkeImgs/alic1.png", "./imgs/SirkeImgs/alic2.png"],
  },
  {
    id: 3,
    title: "Ananas Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/ananas1.png", "./imgs/SirkeImgs/ananas2.png"],
  },
  {
    id: 4,
    title: "Armut Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 50.00", "-"],
    img: ["./imgs/SirkeImgs/armut1.png", "./imgs/SirkeImgs/armut2.png"],
  },
  {
    id: 5,
    title: "Ayva Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 50.00", "-"],
    img: ["./imgs/SirkeImgs/ayva1.png", "./imgs/SirkeImgs/ayva2.png"],
  },
  {
    id: 6,
    title: "Bal Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 100.00", "₺ 55.00"],
    img: ["./imgs/SirkeImgs/bal1.png", "./imgs/SirkeImgs/bal2.png"],
  },
  {
    id: 7,
    title: "Biberiye Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/biberiye1.png", "./imgs/SirkeImgs/biberiye2.png"],
  },
  {
    id: 8,
    title: "Çilek Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/cilek1.png", "./imgs/SirkeImgs/cilek2.png"],
  },
  {
    id: 9,
    title: "Elma Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 50.00", "-"],
    img: ["./imgs/SirkeImgs/elma1.png", "./imgs/SirkeImgs/elma2.png"],
  },
  {
    id: 10,
    title: "Enginar Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 60.00", "₺ 35.00"],
    img: ["./imgs/SirkeImgs/enginar1.png", "./imgs/SirkeImgs/enginar2.png"],
  },
  {
    id: 11,
    title: "Erik Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 60.00", "₺ 35.00"],
    img: ["./imgs/SirkeImgs/erik1.png", "./imgs/SirkeImgs/erik2.png"],
  },
  {
    id: 12,
    title: "Frenk Yemişi Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/frenk1.png", "./imgs/SirkeImgs/frenk2.png"],
  },
  {
    id: 13,
    title: "Gelincik Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 100.00", "₺ 55.00"],
    img: ["./imgs/SirkeImgs/gelincik1.png", "./imgs/SirkeImgs/gelincik2.png"],
  },
  {
    id: 14,
    title: "Gilaboru Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 80.00", "₺ 45.00"],
    img: ["./imgs/SirkeImgs/gilaboru1.png", "./imgs/SirkeImgs/gilaboru2.png"],
  },
  {
    id: 15,
    title: "Hanımeli Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 120.00", "₺ 65.00"],
    img: ["./imgs/SirkeImgs/hanimeli1.png", "./imgs/SirkeImgs/hanimeli2.png"],
  },
  {
    id: 16,
    title: "Hatmi Çiçeği Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 80.00", "₺ 45.00"],
    img: ["./imgs/SirkeImgs/hatmi1.png", "./imgs/SirkeImgs/hatmi2.png"],
  },
  {
    id: 17,
    title: "Hayıt Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/hayit1.png", "./imgs/SirkeImgs/hayit2.png"],
  },
  {
    id: 18,
    title: "Hurma Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 80.00", "₺ 45.00"],
    img: ["./imgs/SirkeImgs/hurma1.png", "./imgs/SirkeImgs/hurma2.png"],
  },
  {
    id: 19,
    title: "Hünnap Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 100.00", "₺ 55.00"],
    img: ["./imgs/SirkeImgs/hunnap1.png", "./imgs/SirkeImgs/hunnap2.png"],
  },
  {
    id: 20,
    title: "Ihlamur Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/ihlamur1.png", "./imgs/SirkeImgs/ihlamur2.png"],
  },
  {
    id: 21,
    title: "Isırgan Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 90.00", "₺ 50.00"],
    img: ["./imgs/SirkeImgs/isirgan1.png", "./imgs/SirkeImgs/isirgan2.png"],
  },
  {
    id: 22,
    title: "Isparta Gülü Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 100.00", "₺ 55.00"],
    img: ["./imgs/SirkeImgs/isparta1.png", "./imgs/SirkeImgs/isparta2.png"],
  },
  {
    id: 23,
    title: "Itır Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/itir1.png", "./imgs/SirkeImgs/itir2.png"],
  },
  {
    id: 24,
    title: "İğde Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 90.00", "₺ 50.00"],
    img: ["./imgs/SirkeImgs/igde1.png", "./imgs/SirkeImgs/igde2.png"],
  },
  {
    id: 25,
    title: "İncir Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/incir1.png", "./imgs/SirkeImgs/incir2.png"],
  },
  {
    id: 26,
    title: "Kabak Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/kabak1.png", "./imgs/SirkeImgs/kabak2.png"],
  },
  {
    id: 27,
    title: "Kadife Çiçeği Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 90.00", "₺ 50.00"],
    img: ["./imgs/SirkeImgs/kadife1.png", "./imgs/SirkeImgs/kadife2.png"],
  },
  {
    id: 28,
    title: "Keçi Boynuzu Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 100.00", "₺ 55.00"],
    img: ["./imgs/SirkeImgs/keci1.png", "./imgs/SirkeImgs/keci2.png"],
  },
  {
    id: 29,
    title: "Kekik Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/kekik1.png", "./imgs/SirkeImgs/kekik2.png"],
  },
  {
    id: 30,
    title: "Kızılcık Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 90.00", "₺ 50.00"],
    img: ["./imgs/SirkeImgs/kizilcik1.png", "./imgs/SirkeImgs/kizilcik2.png"],
  },
  {
    id: 31,
    title: "Kiraz Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/kiraz1.png", "./imgs/SirkeImgs/kiraz2.png"],
  },
  {
    id: 32,
    title: "Kivi Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 90.00", "₺ 50.00"],
    img: ["./imgs/SirkeImgs/kivi1.png", "./imgs/SirkeImgs/kivi2.png"],
  },
  {
    id: 33,
    title: "Kozalak Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/kozalak1.png", "./imgs/SirkeImgs/kozalak2.png"],
  },
  {
    id: 34,
    title: "Kudret Narı Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 100.00", "₺ 55.00"],
    img: ["./imgs/SirkeImgs/kudret1.png", "./imgs/SirkeImgs/kudret2.png"],
  },
  {
    id: 35,
    title: "Kuşburnu Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 90.00", "₺ 50.00"],
    img: ["./imgs/SirkeImgs/kusburnu1.png", "./imgs/SirkeImgs/kusburnu2.png"],
  },
  {
    id: 36,
    title: "Lavanta Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/lavanta1.png", "./imgs/SirkeImgs/lavanta2.png"],
  },
  {
    id: 37,
    title: "Limon Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 50.00", "-"],
    img: ["./imgs/SirkeImgs/limon1.png", "./imgs/SirkeImgs/limon2.png"],
  },
  {
    id: 38,
    title: "Limon-Portakal Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 50.00", "-"],
    img: [
      "./imgs/SirkeImgs/limonportakal1.png",
      "./imgs/SirkeImgs/limonportakal2.png",
    ],
  },
  {
    id: 39,
    title: "Mandalin Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 50.00", "-"],
    img: ["./imgs/SirkeImgs/mandalin1.png", "./imgs/SirkeImgs/mandalin2.png"],
  },
  {
    id: 40,
    title: "Melisa Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/melisa1.png", "./imgs/SirkeImgs/melisa2.png"],
  },
  {
    id: 41,
    title: "Mor Salkım Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 100.00", "₺ 55.00"],
    img: ["./imgs/SirkeImgs/morsalkim1.png", "./imgs/SirkeImgs/morsalkim2.png"],
  },
  {
    id: 42,
    title: "Muşmula Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/musmula1.png", "./imgs/SirkeImgs/musmula2.png"],
  },
  {
    id: 43,
    title: "Nane Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 90.00", "₺ 50.00"],
    img: ["./imgs/SirkeImgs/nane1.png", "./imgs/SirkeImgs/nane2.png"],
  },
  {
    id: 44,
    title: "Nar Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 90.00", "₺ 50.00"],
    img: ["./imgs/SirkeImgs/nar1.png", "./imgs/SirkeImgs/nar2.png"],
  },
  {
    id: 45,
    title: "Pancar Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 70.00", "₺ 40.00"],
    img: ["./imgs/SirkeImgs/pancar1.png", "./imgs/SirkeImgs/pancar2.png"],
  },
  {
    id: 46,
    title: "Reyhan Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 90.00", "₺ 50.00"],
    img: ["./imgs/SirkeImgs/reyhan1.png", "./imgs/SirkeImgs/reyhan2.png"],
  },
  {
    id: 47,
    title: "Şeftali Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 60.00", "₺ 35.00"],
    img: ["./imgs/SirkeImgs/seftali1.png", "./imgs/SirkeImgs/seftali2.png"],
  },
  {
    id: 48,
    title: "Şeftali Çiçeği Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 120.00", "₺ 65.00"],
    img: [
      "./imgs/SirkeImgs/seftalicicegi1.png",
      "./imgs/SirkeImgs/seftalicicegi2.png",
    ],
  },
  {
    id: 49,
    title: "Üzüm Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 50.00", "-"],
    img: ["./imgs/SirkeImgs/uzum1.png", "./imgs/SirkeImgs/uzum2.png"],
  },
  {
    id: 50,
    title: "Yaban Mersini Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 90.00", "₺ 50.00"],
    img: [
      "./imgs/SirkeImgs/yabanmersini1.png",
      "./imgs/SirkeImgs/yabanmersini2.png",
    ],
  },
  {
    id: 51,
    title: "Yeşil Çay Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 100.00", "₺ 55.00"],
    img: ["./imgs/SirkeImgs/yesilcay1.png", "./imgs/SirkeImgs/yesilcay2.png"],
  },
  {
    id: 52,
    title: "Yeşil Zeytin Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 120.00", "₺ 65.00"],
    img: [
      "./imgs/SirkeImgs/yesilzeytin1.png",
      "./imgs/SirkeImgs/yesilzeytin2.png",
    ],
  },
  {
    id: 53,
    title: "Zeytin Yaprağı Sirkesi",
    category: ["500ml", "250ml"],
    price: ["₺ 50.00", "-"],
    img: [
      "./imgs/SirkeImgs/zeytinyapragi1.png",
      "./imgs/SirkeImgs/zeytinyapragi2.png",
    ],
  },
];
